### ISSUE TITLE
Missing url for test in the README

### ISSUE THREAD

**Issue by rikirenz** [Kopano-dev/kapi#1]
Hey Guys,

Could you please add in the README file a link to the url I need to access to test if the application started correctly?

Thanks,
Riccardo

**Comment by fbartels** [comment]
Hi @rikirenz,

there is a /health-check endpoint. See https://github.com/Kopano-dev/kapi/blob/master/cmd/kapid/healthcheck.go#L36-L54

**Comment by fbartels** [comment]
Hi @rikirenz,

was your question answered?
